apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app
spec:
  type: LoadBalancer
  selector:
    app: ping-pong-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http